import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Sidebar from "@/components/Sidebar/Sidebar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My new Next.js App",
  description: "Generated by volt",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen flex flex-col">
          <main className="flex-1">
            <Header />

            <div>{children}</div>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
